### ISSUE TITLE
文章详情 html 里的敏感信息能隐藏掉吗？

### ISSUE THREAD

**Issue by YGragon** [EryouHao/EryouHao.github.io#14]
![image](https://user-images.githubusercontent.com/15891602/58675099-6337c880-8385-11e9-8a83-59e230ba61a2.png)

**Comment by EryouHao** [comment]
这个是[Gitalk](https://github.com/gitalk/gitalk) 要求的，理论上这个 id 和 secret只能应用于你创建 Oauth application 时对应的 Homepage URL 和 callback URL，应该没啥影响。

**Comment by YGragon** [comment]
好的
